version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dna-postgres
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dna-network
  redis:
    image: redis:7
    container_name: dna-redis
    ports:
      - "6379:6379"
    networks:
      - dna-network

volumes:
  pgdata:

networks:
  dna-network:
