[build]
builder = "NIXPACKS"
# Fase de compilación ─ empaquetamos el .jar
cmd = "chmod +x mvnw && ./mvnw -DskipTests clean package"

[start]
cmd  = "java -jar target/mutants-1.0.0.jar"

[build.args]
JAVA_VERSION = "21"